version: '3'

networks:
  proxy:
    external: true



services: 
  lumen:
    build:
      context: .
      dockerfile: Dockerfile
    image: lumen
    working_dir: /var/www/html
    networks:
      - proxy
    labels:
      - traefik.http.routers.lumen.rule=Host(`lumen.rpi4.kg`)
      - traefik.http.services.home.loadbalancer.server.port=80 
      - traefik.enable=true
